config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :bands, only: [:index, :show, :new, :create] do
    resources :jam_sessions, only: [:create]
  end

  resources :jam_sessions, only: [:update, :destroy]
  resources :users, only: [:show]
end

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="logo">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
        <!-- Profile picture with dropdown list -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <% if current_user.photo.present? %>
              <%= cl_image_tag current_user.photo, class:"avatar dropdown-toggle", alt:"Avatar", id:"navbar-wagon-menu", data: { toggle: 'dropdown' } %>
            <% else %>
            <%= image_tag "no_pic.png", class:"avatar dropdown-toggle", alt:"Avatar", id:"navbar-wagon-menu", data: { toggle: 'dropdown' } %>
            <% end %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li><%= link_to 'Profile', user_path(current_user) %>  </li>
              <% if current_user.bands.present? %>
                <li><%= link_to 'Your band', band_path(current_user.bands.first) %> </li>
              <% else %>
                <li><%= link_to 'Create band', new_band_path(current_user) %> </li>
              <% end %>
              <li><%= link_to destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" do  %>
              <%= t(".sign_out", default: "Log out") %></li>
              <% end %>
            </ul>
          </div>
        </div>
  </div>
    <% else %>
      <!-- When logged out -->
      <%= link_to t(".sign_in", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</div>