config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :bands, only: [:index, :show, :new, :create] do
    resources :jam_sessions, only: [:create]
  end

  resources :jam_sessions, only: [:update, :destroy]
  resources :users, only: [:show]
end

app/models/band.rb
class Band < ApplicationRecord
  belongs_to :user
  has_many :jam_sessions
  has_many :users, through: :jam_sessions
  validates :name, presence: true
  validates :genre, presence: true
  validates :address, presence: true
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      sql_query = " \
        name @@ :query \
        OR genre @@ :query \
        OR description @@ :query \
        OR address @@ :query \
      "
      @bands = Band.where(sql_query, query: "%#{params[:query]}%")
    else
      @bands = Band.all
    end

  end

  def show
    @band = Band.find(params[:id])
    @markers = [{ lat: @band.latitude, lng: @band.longitude }]

    if current_user
      @jam_session = current_user.jam_sessions.find_by(band: @band) || JamSession.new
    else
      @jam_session = JamSession.new
    end
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    @band.user = current_user
    if @band.save
      redirect_to band_path(@band)
    else
      render :new
    end
  end

  private

  def band_params
    params.require(:band).permit(:name, :genre, :address, :photo, :instrument, :description)
  end

end

app/views/bands/_connect_form.html.erb
<%= simple_form_for([band, jam_session], remote: true) do |f| %>
  <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
  <%= f.submit "Connect", class:"connect-btn" %>
<% end %>

app/views/bands/create.js.erb
import swal from 'sweetalert';

console.log('create runned!')

function refreshInner(innerHTML) {
  const connectArea = document.getElementById('connect_area');
  connectArea.innerHTML = innerHTML;
}
console.log('create runned!')
<% if @jam_session.errors.any? %>
console.log('error!')
  refreshInner('<%= j render "connect_form" %>');
<% else %>
console.log('no error!')
  refreshInner('<%= j render "pending" %>');
  swal({ title: "Hey !", text: "Your request sent..", icon: "success" });
<% end %>

app/views/bands/index.html.erb
<div class="main-container">
  <h1 class="text-center">Looking for Bands?</h1>

  <center>
      <form method="get" action="/bands" role="search">
        <div class="row">
          <div class="col-xs-6 col-xs-offset-3">
            <div class="input-group">
              <input type="text" class="form-control" name="query" placeholder="Genre, instruments, location...">
              <span class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="fas fa-search"></i></button>
              </span>
            </div>
          </div>
        </div>
      </form>
      <h3 class="text-center"><%= link_to "Or add your band!", new_band_path, class:"btnb btn-primary band-btn" %></h3>
    <center>
  </div>


  <div class="row">
      <div class="container">
        <% @bands.each do |band| %>
          <%= link_to band_path(band) do %>
            <div class="col-xs-12 col-md-4 card-container">
              <div class="card background-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path band.photo if band.photo.present? %>');">
                <div class="content-overlay overlay-left">
                  <div class="text-container">
                    <p class="text-name"><%= band.name %></p>
                    <p class="text-instrument"><strong><%= band.instrument %></strong> player wanted</p>
                    <p class="text-address"><%= band.address %></p>
                  </div>
                </div>
                <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/bands/new.html.erb
<h1 class="text-center sign-up">Create a band</h1>

<div class="container sign-up-container">
  <%= simple_form_for @band do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "name" },
                  placeholder: "Band name"%>
      <%= f.input :genre,
                  required: true,
                  input_html: { autocomplete: "genre" },
                  placeholder: "Genre" %>
      <%= f.input :address,
                  required: true,
                  input_html: { autocomplete: "address"},
                  placeholder: "Which area are you located?" %>
     <%= f.input :instrument,
                  required: true,
                  input_html: { autocomplete: "instrument"},
                  placeholder: "What musician are you looking for?" %>
     <%= f.input :description,
                  required: true,
                  input_html: { autocomplete: "description"},
                  placeholder: "Describe your band ;)" %>
      <%= f.input :photo,
                  required: true %>
      <%= f.input :photo_cache, as: :hidden %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Create", class: "submit-btn" %>
    </div>
  <% end %>
</div>

app/views/bands/show.html.erb
<div class="cover-photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @band.photo if @band.photo.present? %>');">
</div>
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-7">
      <div id="band-info" class="text-center profile-card">
        <h1><%= @band.name %></h1>
        <p>(Usually meet up near <%= @band.address %>)</p>
        <p><strong>Genre: <%= @band.genre %></strong></p>
      </div>
      <div class="text-center profile-card">
        <% if @band.description.present? %>
        <h4>Band Info & Announcements</h4>
        <p style="white-space: pre-line;"><%= @band.description %></p>
        <% else %>
          <p>No Description.</p>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-md-5" id="map" style="width: 474px; height: 500px;" data-markers="<%= @markers.to_json %>">
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <!-- Connect Form -->
      <div class="request-card">
      <% if current_user.present? && current_user.id == @band.user_id %>
        <ul class="list-inline">
          <% @band.jam_sessions.each do |session| %>
            <% if session.status.downcase == 'pending' %>
              <li class="request-content">
                <%= cl_image_tag session.user.photo, class:"avatar", alt:"Avatar" %>
                <%= link_to session.user.name, user_path(session.user), class: "user_name" %> wants to join your band.
                <%= link_to '+ Accept', jam_session_path(session), method:'patch', class:'btn btn-success' %>
                <%= link_to 'x Decline', jam_session_path(session), data: { confirm: 'Are you sure?' }, method:'delete', class:'btn btn-danger' %>
              </li>
            <% end %>
            <% if session.status.downcase == 'accepted' %>
              <li class="request-content">
                <%= cl_image_tag current_user.photo, class: "avatar", alt:"Avatar" %>
                <%= link_to session.user.name, user_path(session.user), class: "user_name" %> in your band!.
              </li>
            <% end %>
          <% end  %>
        </ul>
      <% else %>
        <% if @jam_session.id %>
            <div class="container">
              <%= @jam_session.status %>
            </div>
        <% else %>
          <div class="text-center">
              <div class="form-wrapper text-center" id="connect_area" style="width: 400px; margin: 0 auto;">
                  <h2>Want to Connect?</h2>
                  <%= render 'jam_sessions/connect_form', band: @band, jam_session: @jam_session %>
              </div>
          </div>
        <% end %>
      <% end %>
    </div>

    </div>
  </div>

</div>